version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlflow:/app/mlflow
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: gunicorn --bind 0.0.0.0:5000 src.api.app:app

  mlflow:
    image: python:3.8-slim
    ports:
      - "5001:5001"
    volumes:
      - ./mlflow:/mlflow
    command: >
      bash -c "pip install mlflow==2.6.0 && 
               mlflow server --backend-store-uri /mlflow --host 0.0.0.0 --port 5001"
    depends_on:
      - app 