apiVersion: v1
kind: Service
metadata:
  name: cat-dog-classifier
  labels:
    app: cat-dog-classifier
spec:
  selector:
    app: cat-dog-classifier
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer 